Mng 141 user GET
lukaszdutka/CodersCamp2020.Project.FullStack-Node-React.PikaBook pull request #5
Opened 2021-03-02 21:20 UTC by AgataLudwiczynska

2021-03-02 22:47 UTC, daria305 requested changes

2021-03-02 22:47 UTC, daria305 commented on src/routes/User/Users.ts
> +});
Would be good to add an error handling
```suggestion
router.get('/:id', async(req:Request, res: Response) => {
    try {
        const user = await User.find({_id: req.params.id});
        return res.status(OK).json({user});
    } catch (error) {
        return res.status(BAD_REQUEST).send(error.message);
    }
});
```

2021-03-03 10:16 UTC, AgataLudwiczynska commented on src/routes/User/Users.ts
> +});
Sure, my oversight.

2021-03-03 14:36 UTC, daria305 approved these changes

2021-03-03 14:36 UTC, merged